### ISSUE TITLE
nom::Err: wrong number of type arguments

### ISSUE THREAD

**Issue by focusaurus** [bpressure/nom_pem#7]
So I'm trying to ideally combine rust stable with nom, nom_pem, and der_parser. Both nom_pem and der_parser look like they should work with nom v3 which is fine. I don't care one way or another about rust nightly/stable/beta as long as some combination is compatible. I'm getting the following compile error now trying to use nom_pem 1.0.3 from crates.

```
error[E0243]: wrong number of type arguments: expected at least 1, found 0
  --> /Users/plyons/.cargo/registry/src/github.com-1ecc6299db9ec823/nom_pem-1.0.3/src/lib.rs:63:14
   |
63 |     NomError(nom::Err),
   |              ^^^^^^^^ expected at least 1 type argument

error: aborting due to previous error
```

**Comment by bpressure** [comment]
which rustc-version do you use?

```
rustc -V
```

**Comment by focusaurus** [comment]
Same error with both 1.22.1 (stable) and 1.24.0 (nightly)

```
rustup override set stable && rustc -V && cargo build
info: using existing install for 'stable-x86_64-apple-darwin'
info: override toolchain for '/Users/plyons/projects/tealeaves' set to 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.22.1 (05e2e1c41 2017-11-22)

rustc 1.22.1 (05e2e1c41 2017-11-22)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling nom_pem v1.0.3
error[E0243]: wrong number of type arguments: expected at least 1, found 0
  --> /Users/plyons/.cargo/registry/src/github.com-1ecc6299db9ec823/nom_pem-1.0.3/src/lib.rs:63:14
   |
63 |     NomError(nom::Err),
   |              ^^^^^^^^ expected at least 1 type argument

error: aborting due to previous error

error: Could not compile `nom_pem`.

To learn more, run the command again with --verbose.
```

```
rustup override set nightly && rustc -V && cargo build
info: using existing install for 'nightly-x86_64-apple-darwin'
info: override toolchain for '/Users/plyons/projects/tealeaves' set to 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.24.0-nightly (c8ddf2852 2017-12-07)

rustc 1.24.0-nightly (c8ddf2852 2017-12-07)
   Compiling nom_pem v1.0.3
error[E0243]: wrong number of type arguments: expected at least 1, found 0
  --> /Users/plyons/.cargo/registry/src/github.com-1ecc6299db9ec823/nom_pem-1.0.3/src/lib.rs:63:14
   |
63 |     NomError(nom::Err),
   |              ^^^^^^^^ expected at least 1 type argument

error: aborting due to previous error

error: Could not compile `nom_pem`.

To learn more, run the command again with --verbose.
```

**Comment by bpressure** [comment]
I don't have that issue (rustc 1.24.0-nightly (9fe7aa353 2017-12-11)/rustc 1.22.1 (05e2e1c41 2017-11-22))
travis is fine as well https://travis-ci.org/bpressure/nom_pem

I have to look into it

**Comment by focusaurus** [comment]
Are you updating to the nom v4 alpha? That's the only version I think that exposes a `nom::Err` enum. The nom v3 docs don't have that, they have `nom::IError`.

**Comment by bpressure** [comment]
no

**Comment by focusaurus** [comment]
OK I'm not sure what's going on either. I'm new enough to rust that I could have my environment whacky some how. I'll try to get someone to pair with me on it.

**Comment by bpressure** [comment]
I will look into it...

**Comment by bpressure** [comment]
do you have the feature "verbose-errors" off that is on per default?

**Comment by focusaurus** [comment]
OK a colleague is able to compile nom_pem on stable v1.22.1. It must be something with my tooling setup. I'm going to nuke and pave.

**Comment by focusaurus** [comment]
OK it's trying to combine `nom_pem` and `der-parser` (also based on nom) that reproduces the issue. Hmm...

**Comment by bpressure** [comment]
just refactor the error type. Otherwise I will do so Sa/So

**Comment by focusaurus** [comment]
OK I see you refactored and published v1.0.4. That's great! I'm still getting an error compiling my combination of `nom_pem` and `der-parser` but it's a different error:

```
error[E0308]: mismatched types
  --> /Users/plyons/.cargo/registry/src/github.com-1ecc6299db9ec823/nom_pem-1.0.4/src/parsers.rs:12:51
   |
12 |         if b == 13 { return ::nom::IResult::Error(::nom::ErrorKind::CrLf); }
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^
   |                                                   |
   |                                                   expected enum `nom::Err`, found enum `nom::ErrorKind`
   |                                                   help: try using a variant of the expected type: `nom::Err::Code(::nom::ErrorKind::CrLf)`
   |
   = note: expected type `nom::Err<&[u8]>`
              found type `nom::ErrorKind<_>`

error[E0308]: mismatched types
  --> /Users/plyons/.cargo/registry/src/github.com-1ecc6299db9ec823/nom_pem-1.0.4/src/parsers.rs:17:56
   |
17 |                 Err(_) => return ::nom::IResult::Error(::nom::ErrorKind::Alpha)
   |                                                        ^^^^^^^^^^^^^^^^^^^^^^^
   |                                                        |
   |                                                        expected enum `nom::Err`, found enum `nom::ErrorKind`
   |                                                        help: try using a variant of the expected type: `nom::Err::Code(::nom::ErrorKind::Alpha)`
   |
   = note: expected type `nom::Err<&[u8]>`
              found type `nom::ErrorKind<_>`

   Compiling der-parser v0.4.4
error: aborting due to 2 previous errors
```

**Comment by focusaurus** [comment]
OK I got this working with nom v3.2.1 verbose errors with the following changes in a local branch:

```
diff --git a/Cargo.toml b/Cargo.toml
index bbbb79f..bb3b517 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -10,4 +10,6 @@ license = "MIT"
 repository = "https://github.com/bpressure/nom_pem"
 
 [dependencies]
-nom = "^3.2"
+#nom = "^3.2"
+nom = {version = "^3.1", features = ["verbose-errors"]}
+
diff --git a/src/parsers.rs b/src/parsers.rs
index 5039f77..298a465 100644
--- a/src/parsers.rs
+++ b/src/parsers.rs
@@ -9,12 +9,12 @@ pub fn pem_dashed_string(i: &[u8]) -> ::nom::IResult<&[u8], &str> {
     let mut found = 0;
     for pos in 0..i.len() {
         let b = i[pos];
-        if b == 13 { return ::nom::IResult::Error(::nom::ErrorKind::CrLf); }
+        if b == 13 { return ::nom::IResult::Error(::nom::Err::Code(::nom::ErrorKind::CrLf)); }
         if b == 45 { found += 1 } else { found = 0 }
         if found == 5 {
             match str::from_utf8(&i[..(pos - 4)]) {
                 Ok(s) => return ::nom::IResult::Done(&i[(pos + 1)..], s),
-                Err(_) => return ::nom::IResult::Error(::nom::ErrorKind::Alpha)
+                Err(_) => return ::nom::IResult::Error(::nom::Err::Code(::nom::ErrorKind::Alpha))
             }
         }
     }
```

This will probably suffice for me for now I hope and then maybe everything will work together more seamlessly when upgraded to nom v4.
